### ISSUE TITLE
Version comparison is incorrect

### ISSUE THREAD

**Issue by DevNico** [mix1009/version_check#10]
Given a package version of `3.1.0` and a store version of `3.0.68` the dialog is opening. This should not be the case since the package version has a larger minor version than the store version.

See example with version comparison function of this package. I'd suggest using something like https://pub.dev/packages/version for semver version comparison.

```dart
import 'dart:math' as math;

void main() {
  print(_shouldUpdate('3.1.0', '3.0.68')); // prints true
}


bool _shouldUpdate(String? packageVersion, String? storeVersion) {
  if (packageVersion == storeVersion) return false;

  final arr1 = packageVersion!.split('.');
  final arr2 = storeVersion!.split('.');

  for (int i = 0; i < math.min(arr1.length, arr2.length); i++) {
    int? v1 = int.tryParse(arr1[i]);
    int? v2 = int.tryParse(arr2[i]);

    if (v1 == null || v2 == null) {
      if (arr2[i].compareTo(arr1[i]) > 0) {
        return true;
      }
    } else if (v2 > v1) {
      return true;
    }
  }

  return false;
}
```

**Comment by mix1009** [comment]
Thank you for the detailed bug report.
Thank you also for the pull request, but I don't want to add external dependency to a simple library.
I was able to track the bug, and fix the bug.
I'll do some more testing, and release the update.

**Comment by VictorPadovan1997** [comment]
same error
